# -*- coding: utf-8 -*-
"""440Aissgnment3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fYAfBhg_xioBmRMId5xqrWA-5mWVV5nE

Problem 1

Load the Wine dataset from sklearn.datasets.load_wine()

Split the data into 75 % training and 25 % test sets.

Define a feed‑forward neural network with:

1 hidden layer

32 hidden units

ReLU activation

Output layer: 3 units with softmax activation

Optimizer: Adam

Loss: Categorical cross‑entropy

Epochs: 150

Train the network on the training set.

Print the network’s summary and the accuracy on the test set.

Plot the training and validation loss (or accuracy) curves across epochs.
"""

import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from tensorflow import keras
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, auc

#Load the Wine dataset from sklearn.datasets.load_wine()
wine_dt = load_wine(as_frame=True)
wine_df = wine_dt.frame
print(wine_df)
print("SHape of wine dateset:", wine_df.shape)

#Split the data into 75 % training and 25 % test sets.
x_train, x_test, y_train, y_test = train_test_split(wine_df.drop("target", axis = 1), wine_df["target"], test_size = 0.25, random_state = 42)
print("Shape of x_train:", x_train.shape)
print("Shape of x_test:", x_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

#scaling features
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

#one_hot encoding
if y_train.ndim == 1:
    y_train = to_categorical(y_train, num_classes = 3)
if y_test.ndim == 1:
    y_test = to_categorical(y_test, num_classes = 3)

print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

#model selection
model = keras.Sequential()
model.add(Dense(32, activation = "relu", input_dim = x_train.shape[1]))
model.add(Dense(3, activation = "softmax"))

print(model.summary())

#compiling model
model.compile(optimizer = "adam", loss = "categorical_crossentropy", metrics = ["accuracy"])
print(model.summary())

#training the nn
training = model.fit(x_train, y_train, epochs = 150, batch_size = 32, validation_data = (x_test, y_test))
print(model.summary())

#evaluation
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f"Test Accuracy:, {test_accuracy:.4f}")
print(f"Test Loss: {test_loss:.4f}")

#plotting training n validation loss
fig, (ax1, ax2) = plt.subplots(1, 2, figsize = (12, 4))

ax1.plot(training.history["loss"], label = "Training Loss")
ax1.plot(training.history["val_loss"], label = "Validation Loss")
ax1.set_title("Sequential Model")
ax1.set_xlabel("Epochs")
ax1.set_ylabel("Loss")
ax1.legend()
ax1.grid(True)

#plotting training and accuracy
ax2.plot(training.history["accuracy"], label = "Training Accuracy")
ax2.plot(training.history["val_accuracy"], label = "Validation Accuracy")
ax2.set_title("Sequential Model")
ax2.set_xlabel("Epochs")
ax2.set_ylabel("Accuracy")
ax2.legend()
ax2.grid(True)

"""Problem 2

Use keras.datasets.imdb to load the IMDb movie‑review dataset.Limit the
vocabulary to the top 10,000 most frequent words.

Take the original training set and split it further into 85 % training and 15 % validation.

Define a neural network with:

Use an embedding layer (10,000 input dim, 64 output dim), then a dense layer with 32 ReLU units, and a sigmoid output layer with 1 unit.

Loss: Binary cross‑entropy.

Optimizer: Adam.

Epochs: 10–15

Train the model on the training set..

Evaluate the model on the official test data provided in keras.datasets.imdb.

Print the summary of your network.

Report the test accuracy.

Plot the training and validation loss and accuracy curves.

Draw the ROC curve and calculate the AUC (area under the curve) to evaluate the model’s performance beyond just accuracy.

"""

#imdb dataset
frequent_words = 10000
(x_train, y_train), (x_test, y_test) = keras.datasets.imdb.load_data(num_words = frequent_words)
print(f"training data:, {x_train}")
print(f"testing data:, {x_test}")
print(f"Most frquent words:, {frequent_words}")

#padding
max_length = 500
x_train = keras.preprocessing.sequence.pad_sequences(x_train, maxlen = max_length)
x_test = keras.preprocessing.sequence.pad_sequences(x_test, maxlen = max_length)
print(f"training data:, {x_train}")
print(f"testing data:, {x_test}")

#training, testing
xtrain, xtest, ytrain, ytest = train_test_split(x_train, y_train, test_size = 0.15, random_state = 42)
xtrain = np.array(xtrain).astype("float32")
ytrain = np.array(ytrain).astype("float32")
xtest = np.array(xtest).astype("float32")
ytest = np.array(ytest).astype("float32")

#model
from tensorflow.keras.layers import Flatten
model = keras.Sequential()
model.add(keras.layers.Embedding(input_dim = frequent_words, output_dim = 64))
model.add(Flatten())
model.add(Dense(32, activation = "relu"))
model.add(Dense(1, activation = "sigmoid"))

#compiling model
model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

#training
training1 = model.fit(xtrain, ytrain, epochs = 15, batch_size = 32, validation_data = (xtest, ytest))

#print summary of your report
test_loss, test_accuracy = model.evaluate(xtest, ytest)
print(f"Test Accuracy:, {test_accuracy:.4f}")
print(f"Test Loss: {test_loss:.4f}")

print(model.summary())

#plot training n validation loss and accuracy curves
fig, (ax1, ax2) = plt.subplots(1, 2, figsize = (18, 4))
#training and validation loss
ax1.plot(training1.history["loss"], label="Training Loss")
ax1.plot(training1.history["val_loss"], label="Validation Loss")
ax1.set_title("Training and Validation Loss")
ax1.set_xlabel("Epochs")
ax1.set_ylabel("Loss")
ax1.legend()
ax1.grid(True)

#training and accuracy
ax2.plot(training1.history["accuracy"], label="Training Accuracy")
ax2.plot(training1.history["val_accuracy"], label="Validation Accuracy")
ax2.set_title("Training and Validation Accuracy")
ax2.set_xlabel("Epochs")
ax2.set_ylabel("Accuracy")
ax2.legend()
ax2.grid(True)

#ROC Curve and calculate AUC to evaluate model's performance beyond accuracy
fig, ax3 = plt.subplots(figsize=(8, 6))
y_predict = model.predict(xtest)
fpr, tpr, thresholds = roc_curve(ytest, y_predict)
roc_auc = auc(fpr, tpr)
print(f"AUC: {roc_auc:.4f}")

ax3.plot(fpr, tpr, color="darkorange", lw=2, label=f"ROC Curve (AUC = {roc_auc:.4f})")
ax3.plot([0, 1], [0, 1], color="navy", lw=2, linestyle="--")
ax3.set_xlim([0.0, 1.0])
ax3.set_ylim([0.0, 1.05])
ax3.set_xlabel("False Positive Rate")
ax3.set_ylabel("True Positive Rate")
ax3.set_title("ROC Curve")
ax3.legend(loc="lower right")
ax3.grid(True)

print(f"Final Results:")
print(f"Test Accuracy: {test_accuracy:.4f}")
print(f"AUC Score: {roc_auc:.4f}")
print(f"Test Loss: {test_loss:.4f}")

"""Problem 3

Reuse the preprocessed data from Question 2.

Take the original training set and split it further into 80 % training and 20 % validation.

Use an embedding layer (output dimension = 64) followed by three hidden dense layers:

Hidden Layer 1: 128 units, ReLU, Dropout = 0.3.

Hidden Layer 2: 64 units, ReLU, Dropout = 0.3.

Hidden Layer 3: 32 units, ReLU.

Output layer: 1 unit, sigmoid activation.

Loss: Binary cross‑entropy.

Optimizer: Adam.

Epochs: 15–20.

Train the model on the training set, then compare the shallow model from Question 2 with the deep model in terms of training time, test accuracy, overfitting (difference between training and validation performance), and confusion matrices. Summarize which model performs better overall and justify your conclusion.

"""

#imdb dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.imdb.load_data(num_words = frequent_words)
print(f"training data:, {x_train}")
print(f"testing data:, {x_test}")
print(f"Most frquent words:, {frequent_words}")

#padding
max_length = 500
x_train = keras.preprocessing.sequence.pad_sequences(x_train, maxlen = max_length)
x_test = keras.preprocessing.sequence.pad_sequences(x_test, maxlen = max_length)
print(f"training data:, {x_train}")
print(f"testing data:, {x_test}")

#splitting to 80-20 ratio
#counting this one deep model training
xtrain, xtest, ytrain, ytest = train_test_split(x_train, y_train, test_size = 0.20, random_state = 42)
xtrain = np.array(xtrain).astype("float32")
ytrain = np.array(ytrain).astype("float32")
xtest = np.array(xtest).astype("float32")
ytest = np.array(ytest).astype("float32")

#shallow model comparison
xtrain_shallow, xtest_shallow, ytrain_shallow, ytest_shallow = train_test_split(x_train, y_train, test_size = 0.15, random_state = 42)
xtrain_shallow = np.array(xtrain_shallow).astype("float32")
ytrain_shallow = np.array(ytrain_shallow).astype("float32")
xtest_shallow = np.array(xtest_shallow).astype("float32")
ytest_shallow = np.array(ytest_shallow).astype("float32")

#shallow model
import time
start_time = time.time()
shallow_model = keras.Sequential()
shallow_model.add(keras.layers.Embedding(input_dim = frequent_words, output_dim = 64))
shallow_model.add(Flatten())
shallow_model.add(Dense(32, activation = "relu"))
shallow_model.add(Dense(1, activation = "sigmoid"))

#shallow model compiling
shallow_model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

#shallow model training
shallow_training = shallow_model.fit(xtrain_shallow, ytrain_shallow, epochs = 20, batch_size = 32, validation_data = (xtest_shallow, ytest_shallow))
shallow_training_time = time.time() - start_time

#deep  model
from tensorflow.keras.layers import Dropout
import time
start_time = time.time()
deep_model = keras.Sequential()
deep_model.add(keras.layers.Embedding(input_dim = frequent_words, output_dim = 64))
deep_model.add(Flatten())
deep_model.add(Dense(128, activation = "relu"))
deep_model.add(Dropout(0.3))
deep_model.add(Dense(64, activation = "relu"))
deep_model.add(Dropout(0.3))
deep_model.add(Dense(32, activation = "relu"))
deep_model.add(Dense(1, activation = "sigmoid"))

#compiling
deep_model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

#training
deep_training = deep_model.fit(xtrain, ytrain, epochs = 20, batch_size = 32, validation_data = (xtest, ytest))
deep_training_time = time.time() - start_time

#evaluating models
shallow_test_loss, shallow_test_accuracy = shallow_model.evaluate(xtest_shallow, ytest_shallow)
deep_test_loss, deep_test_accuracy = deep_model.evaluate(xtest, ytest)

#compare in terms of training time
max_time = max(shallow_training_time, deep_training_time)
min_time = min(shallow_training_time, deep_training_time)

print("Model Comparison")
print("Training Time of Models:")
print(f"Shallow Model Training Time: {shallow_training_time:.4f} seconds")
print(f"Deep Model Training Time: {deep_training_time:.4f} seconds")
print(f"Max Model Training time: {max_time:.4f} seconds")
print(f"Min Model Training time: {min_time:.4f} seconds")

#test accuracy
shallow_test_acc = shallow_test_accuracy
deep_test_acc = deep_test_accuracy

print("Model Comparison")
print("Test Accuracy of Models")
print(f"Shallow Model Test Accuracy: {shallow_test_accuracy:.4f}")
print(f"Deep Model Test Accuracy: {deep_test_accuracy:.4f}")
print(f"Winner: {'Shallow' if shallow_test_acc > deep_test_acc else 'Deep'} Model (higher accuracy)")

#plotting accuracy
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 4))

# Plot accuracy comparison
ax1.plot(shallow_training.history["accuracy"], label="Shallow Training Accuracy", color='blue', linestyle='-')
ax1.plot(shallow_training.history["val_accuracy"], label="Shallow Validation Accuracy", color='blue', linestyle='--')
ax1.plot(deep_training.history["accuracy"], label="Deep Training Accuracy", color='red', linestyle='-')
ax1.plot(deep_training.history["val_accuracy"], label="Deep Validation Accuracy", color='red', linestyle='--')
ax1.set_title("Training and Validation Accuracy")
ax1.set_xlabel("Epochs")
ax1.set_ylabel("Accuracy")
ax1.legend()
ax1.grid(True)

# Plot loss comparison
ax2.plot(shallow_training.history["loss"], label="Shallow Training Loss", color='blue', linestyle='-')
ax2.plot(shallow_training.history["val_loss"], label="Shallow Validation Loss", color='blue', linestyle='--')
ax2.plot(deep_training.history["loss"], label="Deep Training Loss", color='red', linestyle='-')
ax2.plot(deep_training.history["val_loss"], label="Deep Validation Loss", color='red', linestyle='--')
ax2.set_title("Training and Validation Loss")
ax2.set_xlabel("Epochs")
ax2.set_ylabel("Loss")
ax2.legend()
ax2.grid(True)

plt.tight_layout()
plt.show()

#overfitting (difference between training and validation performance)
shallow_final_train_acc = shallow_training.history['accuracy'][-1]
shallow_final_val_acc = shallow_training.history['val_accuracy'][-1]
shallow_overfitting = shallow_final_train_acc - shallow_final_val_acc

deep_final_train_acc = deep_training.history['accuracy'][-1]
deep_final_val_acc = deep_training.history['val_accuracy'][-1]
deep_overfitting = deep_final_train_acc - deep_final_val_acc
print("Model Comparison")
print("Overfitting of Models")
print(f"Shallow Model Overfitting: {shallow_overfitting:.4f}")
print(f"Deep Model Overfitting: {deep_overfitting:.4f}")
print(f"Winner: {'Shallow' if shallow_overfitting < deep_overfitting else 'Deep'} Model (less overfitting)")

#shallow model cm
import seaborn as sns
shallow_predict = (shallow_model.predict(xtest_shallow) > 0.5).astype("int32")
cm_shallow = confusion_matrix(ytest_shallow, shallow_predict.flatten())

fig, axes = plt.subplots(1, 2, figsize = (12,5))

# Plot for shallow model
sns.heatmap(cm_shallow, annot = True, fmt = "d", cmap = "Blues", ax=axes[0])
axes[0].set_title("Confusion Matrix for Shallow Model")
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("Actual")

#deep model cm
deep_predict = (deep_model.predict(xtest) > 0.5).astype("int32")
cm_deep = confusion_matrix(ytest, deep_predict.flatten())

# Plot for deep model
sns.heatmap(cm_deep, annot = True, fmt = "d", cmap = "Blues", ax=axes[1])
axes[1].set_title("Confusion Matrix for Deep Model")
axes[1].set_xlabel("Predicted")
axes[1].set_ylabel("Actual")

plt.tight_layout()
plt.show()

#Summarize which model performs better overall
#justify your conclusion.
model_info = ["Test Accuracy", "Training Time", "Overfitting"]
shallow_values = [shallow_test_acc, shallow_training_time, shallow_overfitting]
deep_values = [deep_test_acc, deep_training_time, deep_overfitting]

shallow_params = shallow_model.count_params()
deep_params = deep_model.count_params()
#plotting
fig, axes = plt.subplots(1, 2, figsize = (12, 4))
shallow_bar = axes[0].bar(model_info, shallow_values, color = "blue")
deep_bar = axes[1].bar(model_info, deep_values, color = "blue")

shallow_score = 0
deep_score = 0

if shallow_training_time < deep_training_time:
    shallow_score += 1
else:
    deep_score += 1

if shallow_test_acc > deep_test_acc:
    shallow_score += 1
else:
    deep_score += 1

if abs(shallow_overfitting) < abs(deep_overfitting):
    shallow_score += 1
else:
    deep_score += 1

winner = "Shallow" if shallow_score > deep_score else "Deep"

print(f"\nOVERALL WINNER: {winner.upper()} MODEL")
print(f"\nJustification:")

if winner == "Shallow":
    print("• The shallow model performs better overall because:")
    print("  - Faster training time with similar or better accuracy")
    print("  - Less prone to overfitting due to fewer parameters")
    print("  - Simpler architecture is more interpretable and maintainable")
    print("  - Sufficient complexity for this binary classification task")
else:
    print("• The deep model performs better overall because:")
    print("  - Higher test accuracy indicates better generalization")
    print("  - More complex architecture can capture subtle patterns")
    print("  - Dropout layers help prevent overfitting")
    print("  - Better feature representation through multiple hidden layers")

print(f"\nKey Insights:")
print(f"• Parameter difference: Deep model has {deep_params:,} vs Shallow model's {shallow_params:,} parameters")
print(f"• The {'deep' if deep_test_acc > shallow_test_acc else 'shallow'} model achieved {max(deep_test_acc, shallow_test_acc):.4f} test accuracy")
print(f"• Overfitting is {'more' if abs(deep_overfitting) > abs(shallow_overfitting) else 'less'} problematic in the deep model")

print("\nModel training and comparison completed!")

"""Problem 4

You are tasked with building an autoencoder model to reconstruct text data from the IMDb movie review dataset. Start by using keras.datasets.imdb to load the dataset.

Autoencoder Architecture:
    • Encoder
         • Input layer: 10,000 units
         • Dense layer: 256 units, ReLU
         • Dense layer: 64 units, ReLU
     • Decoder
         • Dense layer: 256 units, ReLU
        • Output layer: 10,000 units, sigmoid or linear

Loss: Binary cross‑entropy.
Optimizer: Adam
Epochs: ~20–30
Batch size: ~128

After training the model, plot the training and validation loss curves to visualize the performance during training. Then, calculate the reconstruction error on the test set . Finally, compute the cosine similarity between the original and reconstructed vectors to evaluate how similar the reconstructed text is to the original.

"""

#imdb dataset
max_features = 10000
(x_train, y_train), (x_test, y_test) = keras.datasets.imdb.load_data(num_words = max_features)

#processing
def vectorize_sequences(sequences, dimension = 10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.0
        return results
x_train_vec = vectorize_sequences(x_train)
x_test_vec = vectorize_sequences(x_test)

print(f"training data: {x_train.shape}")
print(f"testing data: {x_test.shape}")

#autoEncoder
#encoder
from tensorflow.keras import layers
max_features =10000
input_layer = keras.Input(shape = (max_features,))
encoder = keras.layers.Dense(256, activation = "relu")(input_layer)
encoder = keras.layers.Dense(64, activation = "relu")(encoder)

#decoder
decoder = keras.layers.Dense(256, activation = "relu")(encoder)
decoder = keras.layers.Dense(max_features, activation = "sigmoid")(decoder)

#autoencoder
autoencoder = keras.Model(input_layer, decoder)
print("AutoEncoder Model done")

#compiling model
autoencoder.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
print("Model compiled")
print(autoencoder.summary())

#model training
training3 = autoencoder.fit(x_train_vec, x_train_vec, epochs = 30, batch_size = 128, validation_data = (x_test_vec, x_test_vec))
print("Model Training done")

#plotting the trained model
plt.figure(figsize = (10, 5))
plt.subplot(1,2,1)
plt.plot(training3.history["loss"], label = "Training Loss")
plt.plot(training3.history["val_loss"], label = "Validation Loss")
plt.title("Training and Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()

plt.subplot(1,2,2)
plt.plot(training3.history["accuracy"], label = "Training Accuracy")
plt.plot(training3.history["val_accuracy"], label = "Validation Accuracy")
plt.title("Training and Validation Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()

plt.tight_layout()
plt.show()

#reconstruct
reconstruct = autoencoder.predict(x_test_vec)
print(f"Original data: {x_test_vec.shape}")
print(f"Reconstructed data: {reconstruct.shape}")

#reconstruct error on the test set
reconstruction_error = np.mean(np.square(x_test_vec - reconstruct))
print(f"Reconstruction Error:, {reconstruction_error:.4f}")

#cosine similarity between og and rc vectors
#how similar?
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarities = []
for i in range(len(x_test_vec)):
    original = x_test_vec[i].reshape(1, -1)
    reconstructed = reconstruct[i].reshape(1, -1)
    similarity = cosine_similarity(original, reconstructed)[0,0]
    cosine_similarities.append(similarity)

cosine_similarities = np.array(cosine_similarities)
print(f"Cosine Similarity:, {cosine_similarities}")

#plotting cosine similarity
plt.figure(figsize = (10, 5))
plt.hist(cosine_similarities, bins=50, alpha=0.7)
plt.title("Cosine Similarity")
plt.xlabel("Cosine Similarity")
plt.ylabel("Frequency")
plt.axvline(np.mean(cosine_similarities), color="red", linestyle="--", label=f"Mean: {np.mean(cosine_similarities):.4f}")

plt.legend()
plt.show()